export const VIEWCONSTANT = {
    TotalSessions : 'Total Sessions',
    AvgDuration : 'Avg Duration',
    AvgSessionPerDay : 'Avg Session Per Day',
    WeekdayConsumption : 'Weekday Consumption',
    WeekendConsumption : 'Weekend Consumption',
    EnergyConsumed : 'Energy Consumed',
    KWH : 'kWH',
    WH : 'Wh',
    Day : 'day',
    Week : 'week',
    Month : 'month',
    FilterType : 'filterType',
    SVGAElementtartDate :'startDate',
    EndDate : 'endDate',
    ChargerId : 'chargerId',
    OffsetFilter : 'offsetFilter',
    API_FAILED_MSG : 'Failed to fetch data',
    Sessions : 'Sessions',
    UsagekWh : 'Usage kWh',
    FuelMix : 'Fuel Mix',
    Emission : 'Emission',
    OffsetFilter : 'OffsetFilter',
    ChargerID : 'ChargerID',
    DateRange : 'DateRange',
    Sessions : 'Sessions',
    ChargerID_Op : 'Charger ID',
    OffSetFilter_Op : 'OffSet Filter',
    Daily : 'Daily',
    Weekly : 'Weekly',
    Monthly : 'Monthly',
    ValidationMessage :'Please ensure all required fields are filled out correctly.',
    ProfileSucessMsg : 'Charging Profile applied to charger',
    ProfileFailedMsg : 'Failed to set Charging Profile to charger as Charger is Offline.!',
    APIFailedMsg : 'Error in response, status not 1 or message not success.',
    OffLineChargerMsg : 'The profile cannot be applied because the charger is offline.',
    Operative : 'Operative',
    InOperative : 'InOperative',
    ClearChargingProfileMsg : 'Charger profile cleared successfully!',
    ClearChargingProfileFailed : 'Failed to clear charger profile!',
    ClearChargingProfileApiFail : "Error occurred while clearing charger profile!",
    OpeartionalSuccess : 'Operational status changed successfully!',
    OperationFailed : 'Failed to change operational status!',
    OperationAPIFailed : 'Error occurred while changing operational status!',
    ChargerProfile : 'Charger Profile',
    ClearProfile : 'Clear Profile',
    ClearChargingProfileMsgRejected : 'Failed to Clear Applied Charger Profile!',
    Enable : 'Enable',
    Disable : 'Disable'


}